// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var PersonId = require("./PersonId.bs.js");

var bobId = Curry._1(PersonId.random, undefined);

var bobValue = Curry._1(PersonId.value, bobId);

console.log("Bob's id is " + bobValue);

exports.bobId = bobId;
exports.bobValue = bobValue;
/* bobId Not a pure module */
