// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UniqueId from "./UniqueId.bs.js";

var include = UniqueId.Make({});

var makeUnsafe = include.makeUnsafe;

var make = include.make;

var makeOpt = include.makeOpt;

var value = include.value;

var random = include.random;

var _ignore = 0;

export {
  makeUnsafe ,
  make ,
  makeOpt ,
  value ,
  random ,
  _ignore ,
}
/* include Not a pure module */
