// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var UniqueId = require("./UniqueId.bs.js");

var include = UniqueId.Make({});

var makeUnsafe = include.makeUnsafe;

var make = include.make;

var makeOpt = include.makeOpt;

var value = include.value;

var random = include.random;

var _ignore = 0;

exports.makeUnsafe = makeUnsafe;
exports.make = make;
exports.makeOpt = makeOpt;
exports.value = value;
exports.random = random;
exports._ignore = _ignore;
/* include Not a pure module */
