// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as PersonId from "./PersonId.bs.js";

var bobId = Curry._1(PersonId.random, undefined);

var bobValue = Curry._1(PersonId.value, bobId);

console.log("Bob's id is " + bobValue);

export {
  bobId ,
  bobValue ,
}
/* bobId Not a pure module */
