// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Validated = require("./Validated.bs.js");

function Make($star) {
  var validate = function (s) {
    var s$1 = s.trim();
    var len = s$1.length;
    if (len < 5) {
      return {
              TAG: /* Error */1,
              _0: /* InvalidFormat */0
            };
    } else {
      return {
              TAG: /* Ok */0,
              _0: s$1
            };
    }
  };
  var include = Validated.Make({
        validate: validate
      });
  var makeUnsafe = include.makeUnsafe;
  var random = function (param) {
    return Curry._1(makeUnsafe, "uuid:" + String(Math.random()));
  };
  return {
          makeUnsafe: makeUnsafe,
          make: include.make,
          makeOpt: include.makeOpt,
          value: include.value,
          random: random
        };
}

exports.Make = Make;
/* No side effect */
