// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

function Make(P) {
  var make = function (__x) {
    return P.validate(__x);
  };
  var makeOpt = function (i) {
    var v = P.validate(i);
    if (v.TAG === /* Ok */0) {
      return Caml_option.some(v._0);
    }
    
  };
  return {
          makeUnsafe: (function (prim) {
              return prim;
            }),
          make: make,
          makeOpt: makeOpt,
          value: (function (prim) {
              return prim;
            })
        };
}

exports.Make = Make;
/* No side effect */
